### ISSUE TITLE
Plugin Disabled On 1.14.4 Server [Bug]

### ISSUE THREAD

**Issue by OverboredThekid** [MyWarp/MyWarp#218] opened 2019-08-09 00:29 UTC
### Description of the Problem
The plugin is disabled on my server but everything else is working fine.

### Steps to Reproduce
by starting up the server.

### Log Output
```
08.08 20:22:44 [Server] INFO [MyWarp] Enabling MyWarp v3.0.2-SNAPSHOT+travis-b1785.git-9142277476
08.08 20:22:48 [Server] INFO io.github.mywarp.mywarp.internal.h2.message.DbException: (Message 90034 not found) [90034-199]
08.08 20:22:48 [Server] WARN io.github.mywarp.mywarp.internal.h2.message.DbException: (Message 90034 not found) [90034-199]
08.08 20:22:48 [Server] WARN at io.github.mywarp.mywarp.internal.h2.message.DbException.get(DbException.java:194)
08.08 20:22:48 [Server] WARN at io.github.mywarp.mywarp.internal.h2.message.TraceSystem.logWritingError(TraceSystem.java:289)
08.08 20:22:48 [Server] WARN at io.github.mywarp.mywarp.internal.h2.message.TraceSystem.openWriter(TraceSystem.java:310)
08.08 20:22:48 [Server] WARN at io.github.mywarp.mywarp.internal.h2.message.TraceSystem.writeFile(TraceSystem.java:258)
08.08 20:22:48 [Server] WARN at io.github.mywarp.mywarp.internal.h2.message.TraceSystem.write(TraceSystem.java:242)
08.08 20:22:48 [Server] WARN at io.github.mywarp.mywarp.internal.h2.message.Trace.error(Trace.java:194)
08.08 20:22:48 [Server] WARN at io.github.mywarp.mywarp.internal.h2.engine.Database.openDatabase(Database.java:337)
08.08 20:22:48 [Server] WARN at io.github.mywarp.mywarp.internal.h2.engine.Database.<init>(Database.java:313)
08.08 20:22:48 [Server] WARN at io.github.mywarp.mywarp.internal.h2.engine.Engine.openSession(Engine.java:69)
08.08 20:22:48 [Server] WARN at io.github.mywarp.mywarp.internal.h2.engine.Engine.openSession(Engine.java:201)
08.08 20:22:48 [Server] WARN at io.github.mywarp.mywarp.internal.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
08.08 20:22:48 [Server] WARN at io.github.mywarp.mywarp.internal.h2.engine.Engine.createSession(Engine.java:161)
08.08 20:22:48 [Server] WARN at io.github.mywarp.mywarp.internal.h2.engine.Engine.createSession(Engine.java:31)
08.08 20:22:48 [Server] WARN at io.github.mywarp.mywarp.internal.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
08.08 20:22:48 [Server] WARN at io.github.mywarp.mywarp.internal.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
08.08 20:22:48 [Server] WARN at io.github.mywarp.mywarp.internal.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
08.08 20:22:48 [Server] WARN at io.github.mywarp.mywarp.internal.h2.Driver.connect(Driver.java:69)
08.08 20:22:48 [Server] WARN at java.sql.DriverManager.getConnection(DriverManager.java:664)
08.08 20:22:48 [Server] WARN at java.sql.DriverManager.getConnection(DriverManager.java:208)
08.08 20:22:48 [Server] WARN at io.github.mywarp.mywarp.bukkit.util.jdbc.SingleConnectionDataSource.initiate(SingleConnectionDataSource.java:163)
08.08 20:22:48 [Server] WARN at io.github.mywarp.mywarp.bukkit.util.jdbc.SingleConnectionDataSource.getConnection(SingleConnectionDataSource.java:83)
08.08 20:22:48 [Server] WARN at io.github.mywarp.mywarp.warp.storage.WarpStorageFactory.<init>(WarpStorageFactory.java:64)
08.08 20:22:48 [Server] WARN at io.github.mywarp.mywarp.warp.storage.WarpStorageFactory.createAndInitialize(WarpStorageFactory.java:105)
08.08 20:22:48 [Server] WARN at io.github.mywarp.mywarp.MyWarp.initialize(MyWarp.java:110)
08.08 20:22:48 [Server] WARN at io.github.mywarp.mywarp.bukkit.MyWarpPlugin.onEnable(MyWarpPlugin.java:114)
08.08 20:22:48 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
08.08 20:22:48 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
08.08 20:22:48 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
08.08 20:22:48 [Server] WARN at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467)
08.08 20:22:48 [Server] WARN at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381)
08.08 20:22:48 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474)
08.08 20:22:48 [Server] WARN at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:282)
08.08 20:22:48 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:869)
08.08 20:22:48 [Server] WARN at java.lang.Thread.run(Thread.java:748)
08.08 20:22:48 [Server] WARN Caused by: io.github.mywarp.mywarp.internal.h2.jdbc.JdbcSQLNonTransientException: (Message 90034 not found) [90034-199]
08.08 20:22:48 [Server] WARN at io.github.mywarp.mywarp.internal.h2.message.DbException.getJdbcSQLException(DbException.java:502)
08.08 20:22:48 [Server] WARN at io.github.mywarp.mywarp.internal.h2.message.DbException.getJdbcSQLException(DbException.java:427)
08.08 20:22:48 [Server] WARN ... 34 more
08.08 20:22:48 [Server] WARN Caused by: io.github.mywarp.mywarp.internal.h2.message.DbException: (Message 90062 not found) [90062-199]
08.08 20:22:48 [Server] WARN at io.github.mywarp.mywarp.internal.h2.message.DbException.get(DbException.java:205)
08.08 20:22:48 [Server] WARN at io.github.mywarp.mywarp.internal.h2.message.DbException.get(DbException.java:181)
08.08 20:22:48 [Server] WARN at io.github.mywarp.mywarp.internal.h2.store.fs.FilePathDisk.createDirectory(FilePathDisk.java:290)
08.08 20:22:48 [Server] WARN at io.github.mywarp.mywarp.internal.h2.store.fs.FileUtils.createDirectory(FileUtils.java:43)
08.08 20:22:48 [Server] WARN at io.github.mywarp.mywarp.internal.h2.store.fs.FileUtils.createDirectories(FileUtils.java:315)
08.08 20:22:48 [Server] WARN at io.github.mywarp.mywarp.internal.h2.store.fs.FileUtils.createDirectories(FileUtils.java:314)
08.08 20:22:48 [Server] WARN at io.github.mywarp.mywarp.internal.h2.store.fs.FileUtils.createDirectories(FileUtils.java:314)
08.08 20:22:48 [Server] WARN at io.github.mywarp.mywarp.internal.h2.store.fs.FileUtils.createDirectories(FileUtils.java:314)
08.08 20:22:48 [Server] WARN at io.github.mywarp.mywarp.internal.h2.store.fs.FileUtils.createDirectories(FileUtils.java:314)
```

### Affected Version
* MyWarp: 3.0.2-SNAPSHOT=TRAVIS-b1785.git-9142277476
* Minecraft and Bukkit Implementation: 1.14.4

### Additional context
I have a dedicated server, it's working on my old server with the same install but not on my new. Thank you for your help. :D

**Comment by TheE** [comment] 2019-08-28 11:50
I am closing this as it is a duplicate of #216.

I cannot reproduce this. Please try it again with the [latest version of MyWarp](https://mywarp.github.io/builds/1788.html) (make sure to get the `-all version) and report back in #216.

**Closed by TheE** 2019-08-28 11:50 UTC
Labels: t: bug
