### ISSUE TITLE
Error login mywarp with 1.12.2

### ISSUE THREAD

**Issue by MineServidorCraft** [MyWarp/MyWarp#174] opened 2017-10-09 13:54 UTC
````
[15:53:23] [Server thread/ERROR]: Could not load 'plugins/mywarp-bukkit-3.0-beta-4-all.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoSuchMethodError: org.apache.logging.log4j.spi.LoggerContext.getLogger(Ljava/lang/String;)Lorg/apache/logging/log4j/Logger;
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[spigot-1.12.2.jar:git-Spigot-7754231-9a1f5ee]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:326) ~[spigot-1.12.2.jar:git-Spigot-7754231-9a1f5ee]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:248) [spigot-1.12.2.jar:git-Spigot-7754231-9a1f5ee]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:308) [spigot-1.12.2.jar:git-Spigot-7754231-9a1f5ee]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-1.12.2.jar:git-Spigot-7754231-9a1f5ee]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-7754231-9a1f5ee]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NoSuchMethodError: org.apache.logging.log4j.spi.LoggerContext.getLogger(Ljava/lang/String;)Lorg/apache/logging/log4j/Logger;
	at me.taylorkelly.mywarp.internal.slf4j.helpers.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:53) ~[?:?]
	at me.taylorkelly.mywarp.internal.slf4j.LoggerFactory.getLogger(LoggerFactory.java:285) ~[?:?]
	at me.taylorkelly.mywarp.internal.slf4j.LoggerFactory.getLogger(LoggerFactory.java:305) ~[?:?]
	at me.taylorkelly.mywarp.util.MyWarpLogger.<init>(MyWarpLogger.java:43) ~[?:?]
	at me.taylorkelly.mywarp.util.MyWarpLogger.getLogger(MyWarpLogger.java:54) ~[?:?]
	at me.taylorkelly.mywarp.bukkit.MyWarpPlugin.<clinit>(MyWarpPlugin.java:84) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_72]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_72]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.12.2.jar:git-Spigot-7754231-9a1f5ee]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot-1.12.2.jar:git-Spigot-7754231-9a1f5ee]
	... 6 more
````
https://pastebin.com/tT9fT7cJ

**Comment by TheE** [comment] 2017-10-09 14:02
Did you update MyWarp and use `/reload`? If so, please shutdown and restart your server and report back if this fixes the problem.

If the problem persists (or you did not use `/reload`), could you test if the [latest devBuild](https://thee140.ci.cloudbees.com/job/MyWarp%203%20(for%20Bukit%201.7.9.+)/) works?

**Comment by TheE** [comment] 2017-11-09 21:19
Closing, as I cannot reproduce the issue without further information.

**Closed by TheE** 2017-11-09 21:19 UTC
Labels: c: bukkit-imp, t: bug
