### ISSUE TITLE
[Bug] , in economy value

### ISSUE THREAD

**Issue by moda84** [MyWarp/MyWarp#428] opened 2022-04-23 17:41 UTC
### Description of the Problem
Invalid symbol replace ,
How fix it?
![image](https://user-images.githubusercontent.com/44532692/164927008-d5260a85-ad1e-4b72-bc18-c9d773475c11.png)

### Log Output

```
<!-- If appreciable, past the log that shows the error -->
```

### Affected Version
* MyWarp: `<!-- Output of /version MyWarp -->`
3.1.2-SNAPSHOT+GitHub_Action-b183.git-7e0b9b40e0

* Minecraft and Bukkit Implementation: `<!-- Output of /version -->`
Current: git-Purpur-1612 (MC: 1.18.2)*
Previous: git-Purpur-1609 (MC: 1.18.2)

**Comment by TheE** [comment] 2022-04-23 18:02
What language is your client using?

**Comment by moda84** [comment] 2022-09-01 02:05
> What language is your client using?
Russian

**Comment by TheE** [comment] 2023-10-10 08:58
I cannot reproduce the issue using the latest development build, probably it has already been fixed in the translations.

**Closed by TheE** 2023-10-10 08:58 UTC
Labels: t: bug
