### ISSUE TITLE
[Bug] MyWarp not working

### ISSUE THREAD

**Issue by ProdigalCB** [MyWarp/MyWarp#219] opened 2019-08-13 19:01 UTC
I am having issues trying to get MyWarps to work.  Below is my error in console
`````
[03:01:22] [Server thread/INFO]: [MyWarp] Enabling MyWarp v3.0.2-SNAPSHOT+travis-b1785.git-9142277476
[03:01:26] [Server thread/INFO]: io.github.mywarp.mywarp.internal.h2.message.DbException: (Message 90034 not found) [90034-199]
[03:01:26] [Server thread/WARN]: io.github.mywarp.mywarp.internal.h2.message.DbException: (Message 90034 not found) [90034-199]
[03:01:26] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.message.DbException.get(DbException.java:194)
[03:01:26] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.message.TraceSystem.logWritingError(TraceSystem.java:289)
[03:01:26] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.message.TraceSystem.openWriter(TraceSystem.java:310)
[03:01:26] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.message.TraceSystem.writeFile(TraceSystem.java:258)
[03:01:26] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.message.TraceSystem.write(TraceSystem.java:242)
[03:01:26] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.message.Trace.error(Trace.java:194)
[03:01:26] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.engine.Database.openDatabase(Database.java:337)
[03:01:26] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.engine.Database.<init>(Database.java:313)
[03:01:26] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.engine.Engine.openSession(Engine.java:69)
[03:01:26] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.engine.Engine.openSession(Engine.java:201)
[03:01:26] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
[03:01:26] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.engine.Engine.createSession(Engine.java:161)
[03:01:26] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.engine.Engine.createSession(Engine.java:31)
[03:01:26] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
[03:01:26] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
[03:01:26] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
[03:01:26] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.Driver.connect(Driver.java:69)
[03:01:26] [Server thread/WARN]: 	at java.sql.DriverManager.getConnection(DriverManager.java:664)
[03:01:26] [Server thread/WARN]: 	at java.sql.DriverManager.getConnection(DriverManager.java:208)
[03:01:26] [Server thread/WARN]: 	at io.github.mywarp.mywarp.bukkit.util.jdbc.SingleConnectionDataSource.initiate(SingleConnectionDataSource.java:163)
[03:01:26] [Server thread/WARN]: 	at io.github.mywarp.mywarp.bukkit.util.jdbc.SingleConnectionDataSource.getConnection(SingleConnectionDataSource.java:83)
[03:01:26] [Server thread/WARN]: 	at io.github.mywarp.mywarp.warp.storage.WarpStorageFactory.<init>(WarpStorageFactory.java:64)
[03:01:26] [Server thread/WARN]: 	at io.github.mywarp.mywarp.warp.storage.WarpStorageFactory.createAndInitialize(WarpStorageFactory.java:105)
[03:01:26] [Server thread/WARN]: 	at io.github.mywarp.mywarp.MyWarp.initialize(MyWarp.java:110)
[03:01:26] [Server thread/WARN]: 	at io.github.mywarp.mywarp.bukkit.MyWarpPlugin.onEnable(MyWarpPlugin.java:114)
[03:01:26] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[03:01:26] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[03:01:26] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[03:01:26] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467)
[03:01:26] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381)
[03:01:26] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474)
[03:01:26] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:282)
[03:01:26] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:869)
[03:01:26] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[03:01:26] [Server thread/WARN]: Caused by: io.github.mywarp.mywarp.internal.h2.jdbc.JdbcSQLNonTransientException: (Message 90034 not found) [90034-199]
[03:01:26] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.message.DbException.getJdbcSQLException(DbException.java:502)
[03:01:26] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.message.DbException.getJdbcSQLException(DbException.java:427)
[03:01:26] [Server thread/WARN]: 	... 34 more
[03:01:26] [Server thread/WARN]: Caused by: io.github.mywarp.mywarp.internal.h2.message.DbException: (Message 90062 not found) [90062-199]
[03:01:26] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.message.DbException.get(DbException.java:205)
[03:01:26] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.message.DbException.get(DbException.java:181)
[03:01:26] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.store.fs.FilePathDisk.createDirectory(FilePathDisk.java:290)
[03:01:26] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.store.fs.FileUtils.createDirectory(FileUtils.java:43)
[03:01:26] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.store.fs.FileUtils.createDirectories(FileUtils.java:315)
[03:01:26] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.store.fs.FileUtils.createDirectories(FileUtils.java:314)
[03:01:26] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.store.fs.FileUtils.createDirectories(FileUtils.java:314)
[03:01:26] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.store.fs.FileUtils.createDirectories(FileUtils.java:314)
[03:01:26] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.store.fs.FileUtils.createDirectories(FileUtils.java:314)
[03:01:26] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.store.fs.FileUtils.createDirectories(FileUtils.java:314)
[03:01:26] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.message.TraceSystem.openWriter(TraceSystem.java:300)
[03:01:26] [Server thread/WARN]: 	... 31 more
[03:01:26] [Server thread/WARN]: Caused by: io.github.mywarp.mywarp.internal.h2.jdbc.JdbcSQLNonTransientException: (Message 90062 not found) [90062-199]
[03:01:26] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.message.DbException.getJdbcSQLException(DbException.java:502)
[03:01:26] [Server thread/WARN]: 	at io.github.mywarp.mywarp.internal.h2.message.DbException.getJdbcSQLException(DbException.java:427)
[03:01:26] [Server thread/WARN]: 	... 42 more
[03:01:26] [Server thread/ERROR]: [MyWarp] [0;31;1mFailed to initialize warp storage.
io.github.mywarp.mywarp.warp.storage.StorageInitializationException: Connection failed due to an SQLException. Is the configuration valid?
	at io.github.mywarp.mywarp.warp.storage.WarpStorageFactory.<init>(WarpStorageFactory.java:72)
	at io.github.mywarp.mywarp.warp.storage.WarpStorageFactory.createAndInitialize(WarpStorageFactory.java:105)
	at io.github.mywarp.mywarp.MyWarp.initialize(MyWarp.java:110)
	at io.github.mywarp.mywarp.bukkit.MyWarpPlugin.onEnable(MyWarpPlugin.java:114)
````

**Comment by TheE** [comment] 2019-08-28 11:50
I am closing this as it is a duplicate of #216.

I cannot reproduce this. Please try it again with the [last version of MyWarp](https://mywarp.github.io/builds/1788.html) (make sure to get the `-all version) and report back in #216 .

**Closed by TheE** 2019-08-28 11:50 UTC
