### ISSUE TITLE
MyWarp broken for 1.12, error on enable.

### ISSUE THREAD

**Issue by wesley27** [MyWarp/MyWarp#148] opened 2017-06-08 18:15 UTC
MyWarp doesn't load in 1.12.

Upon starting the server: https://pastebin.com/7bUykSVr
Upon running a /warp command: https://pastebin.com/UN3eapE7

Thanks!

**Comment by TheE** [comment] 2017-06-08 18:20
This appears to be caused by Spigot's update of Guava to 21.

I am going to update MyWarp for Java8, removing the need for most of Guava's functions (see #71). In fact this is already written, but still needs to be tested.

**Comment by TheE** [comment] 2017-06-09 11:46
Latest devBuild should work fine, but now requires Java8 (as does Minecraft 1.12).
If you continue to notice any errors, feel free to reopen this ticket.

**Comment by wesley27** [comment] 2017-06-09 12:49
The lates dev build gives the same error on enabling: https://pastebin.com/A4vHghTe

Maybe you just pushed the wrong build? :P

I'm running java 8, spigot 1.12, and the latest dev build from an hour ago.

**Comment by TheE** [comment] 2017-06-09 12:53
Seems like the problem is actual Intake. Will look into it.

**Comment by TheE** [comment] 2017-06-09 14:30
Should be fixed now. Could you give the latest devBuild a try?

I just have some minor problems with the H2 databases within my testing environment. Are you by chance using H2 and could give me a list of the names of all files within you MyWarp plugin directory?

**Comment by wesley27** [comment] 2017-06-10 18:30
Update for you:

It appears the most recent dev build is actually working fine. Yesterday afternoon I tried a live load of it without restarting the server, and it failed to enable. This could have happened for a number of reasons with the live load, most likely being due to the failed enabling of the earlier dev build within the same server instance.

At 4am my server automatically restarted and it loaded fine, and is working.

Thanks for the update, cheers!

**Closed** 2017-06-12 10:12 UTC
Labels: c: bukkit-imp, c: core, t: bug

**Comment by TheE** [comment] 2017-06-12 10:14
Thanks, should be fixed in the latest devBuild.

On a side note, in the future please add another comment or another ticket altogether if you want to add something important to the issue or discover a new one. I do not receive mail or IDE notifications for edits and am likely to miss your (very important) addition. 😄
