### ISSUE TITLE
Warps located in unloaded chunks do not set facing direction when activated by pressure plate

### ISSUE THREAD

**Issue by tatedeterra** [MyWarp/MyWarp#223] opened 2019-11-07 16:20 UTC
### Description of the Problem
When warping to a set warp outside the currently loaded chunks via pressure plate, the players facing direction is not updated to the set facing direction of the warp

### Steps to Reproduce
set a warp, move far enough away so the chunk unloads, and face a different direction when stepping on a pressure plate with a warp sign underneath it

### Affected Version
* MyWarp: ` <mywarp-bukkit-3.0.2-SNAPSHOT-all> `
* Minecraft and Bukkit Implementation: `<Spigot Minecraft 1.14.4> `

**Comment by TheE** [comment] 2019-11-21 12:31
Thanks, I see what you mean. I think that, immediately after the teleport, the facing of the teleported player correctly set to the warp's facing and shortly afterwards is set to the old facing.

I am not sure what causes this, since the PlayerInteractEvent is cancelled if the player uses a warp. This may be an error in MC or Spigot. Until I know exactly what is going on, I will likely not be able to fix this.

**Comment by TheE** [comment] 2019-12-02 11:01
Could you give the [latest development build](https://mywarp.github.io/builds/) (1818) a try? Locally it seems to solve the issue.

**Comment by tatem8** [comment] 2019-12-02 13:03
Issue still seems to be present in my case; It's now more noticeable that warping does initially set the correct facing direction initially but then sets the old facing direction immediately after just like you said.
I want to say I really appreciate the time you're taking to update your plugin and respond to others (i know this isnt related to the bug lol) but it is very kind :)

**Comment by TheE** [comment] 2019-12-05 10:33
Alright. Whenever the teleport fails, a corresponding `<Player> moved too quickly!` message is displayed in the console. This seems like a problem caused by Vanilla MC, see [SPIGOT-5292](https://hub.spigotmc.org/jira/browse/SPIGOT-5292). 

I was able to get around the problem by disabling the moved-to-quickly checks altogether by setting `settings.moved-too-quickly-multiplier` in `spigot.yml` to a higher value, but I would not recommend doing this in production.

I am leaving this ticket open for now, but I fear that the issue will only be fixed by future updates to MC (or Spigot).

Also, thanks for your kind words. :)

**Comment by TheE** [comment] 2022-08-17 08:22
Closing this, as it is defiantly a Vanilla issue that is unlikely to be fixable by MyWarp (or Spigot).

**Closed by TheE** 2022-08-17 08:22 UTC
Labels: t: bug, c: bukkit-imp
