### ISSUE TITLE
Option to disable warps with the same name but with a other uppercrase/lowercase form

### ISSUE THREAD

**Issue by Blockbude** [MyWarp/MyWarp#42] opened 2015-04-29 08:17 UTC
Players can create different warps based on the uppercase and lowercase of letters:

WarpTest is different warp than warptest 

A option to disable this would be pretty nice.

**Comment by TheE** [comment] 2015-04-29 18:19
Yes, I am going to implement an option for case insensitive warp names at some point.

**Comment by kelseypolo** [comment] 2016-03-13 16:20
Is there an update on this feature? We would really like the option to disable case insensitive warp names.

**Comment by TheE** [comment] 2017-04-13 22:54
Duplicate of #142.

**Closed by TheE** 2017-04-13 22:54 UTC
Labels: c: bukkit-imp, c: core, s: duplicate, t: feature
